spring:
    application:
      name : hellospring

    datasource:
      url: jdbc:mysql://localhost:3306/hr
      username: chill
      password: chill
      driver-class-name: com.mysql.cj.jdbc.Driver

    messages:
      basename: messages
      encoding: UTF-8
      cache-duration: 0

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true


server:
  error:
    whitelabel:
      enabled: false

